const fs = require('fs');
const os = require('os');
const path = require('path');

// Fungsi untuk mendapatkan IP lokal
function getLocalIP() {
  const interfaces = os.networkInterfaces();
  
  // Cari IP yang bukan localhost dan bukan internal
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      // Skip internal (localhost) dan non-IPv4
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  
  return 'localhost'; // fallback
}

// Fungsi untuk membuat file .env
function createEnvFile() {
  const localIP = getLocalIP();
  const apiUrl = `http://${localIP}:5000`;
  
  const envContent = `# DON'T FORGET TO START THE LARAGON SERVER (APACHE + MYSQL)
REACT_APP_API_URL=${apiUrl}

# Auto-generated by setup-env.js
# Your local IP: ${localIP}
# Backend API URL: ${apiUrl}

# MQTT Configuration
REACT_APP_MQTT_BROKER=wss://9e108cb03c734f0394b0f0b49508ec1e.s1.eu.hivemq.cloud:8884/mqtt
REACT_APP_MQTT_USERNAME=Device02
REACT_APP_MQTT_PASSWORD=Device02
`;

  const envPath = path.join(__dirname, '.env');
  
  fs.writeFileSync(envPath, envContent);
  
  console.log('\nFile .env berhasil dibuat otomatis!');
  console.log(`IP Lokal terdeteksi: ${localIP}`);
  console.log(`Backend API URL: ${apiUrl}\n`);
}

// Jalankan
createEnvFile();